---
# Configure Pihole by using a Python virtual environment
# to run a script to update the sqlite3 database with adlists
# and explicit whitelist/blacklist domains

- name: Copy config files to scripts directory on remote
  ansible.builtin.copy:
    src: ../configs/pihole/
    dest: "{{ env_vars.pihole_script_dir }}"
    owner: docker
    group: docker
    mode: '0644'
  become: true
  become_user: docker

- name: Edit the pihole script to ensure the gravity.db location is correct.
  ansible.builtin.lineinfile:
    path: "{{ env_vars.pihole_script_dir }}/update_lists.py"
    search_string: '    db_path ='
    line: '    db_path = "{{ env_vars.pihole_etc_dir }}/gravity.db"'

- name: Create a virtual environment for Python in the scripts directory
  ansible.builtin.command:
    cmd: "python3 -m venv {{ env_vars.pihole_script_dir }}/venv"
    creates: "{{ env_vars.pihole_script_dir }}/venv"
  args:
    chdir: "{{ env_vars.pihole_script_dir }}"
  become: true
  become_user: docker

- name: Install required Python packages in the virtual environment
  ansible.builtin.pip:
    requirements: "{{ env_vars.pihole_script_dir }}/requirements.txt"
    virtualenv: "{{ env_vars.pihole_script_dir }}/venv"
  become: true
  become_user: docker

- name: Run the Pi-hole gravity update script
  ansible.builtin.command:
    cmd: "{{ env_vars.pihole_script_dir }}/venv/bin/python {{ env_vars.pihole_script_dir }}/update_lists.py"
  args:
    chdir: "{{ env_vars.pihole_script_dir }}"
  become: true
  become_user: docker
