---

- name: Deploy RaspAP via Docker Compose
  community.docker.docker_compose_v2:
    project_src: ./docker
    files:
      - raspap.yml
    state: present
  delegate_to: localhost
  become: true
  become_user: root